### GET /
GET http://localhost:6969

### register endpoint POST /auth/register
POST http://localhost:6969/auth/register
Content-Type: application/json

{
    "username": "ram@mail.com",
    "password": "123"
}

### login endpoint POST /auth/login
POST http://localhost:6969/auth/login
Content-Type: application/json

{
    "username": "ram@mail.com",
    "password": "123"
}

### Fetch all todos GET /TODOS (protected)
GET http://localhost:6969/todos
Authorization: <token>

### Create a new todo POST /TODOS (protected)
POST http://localhost:6969/todos
Authorization: <token>
Content-Type: application/json

{
    "task": "Finish task."
}

### Update a todo PUT /TODOS/:ID (protected)
PUT http://localhost:6969/todos/2?page=1
Authorization: <token>
Content-Type: application/json

{
    "completed": 1
}

### Delete a todo DELETE /TODOS/:ID (protected)
DELETE http://localhost:6969/todos/2
Authorization: <token>
